# Based on:
# - https://github.com/marketplace/actions/rebase-upstream
# - https://github.com/imba-tjd/rebase-upstream-action
name: Rebase Upstream
on:
  schedule:
  - cron: "0 0 * * *"  # run everyday
  workflow_dispatch:   # run manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 10  # greater than the number of commits you made
    - uses: ozars/rebase-upstream-action@master
